#HYPERPARAMETERS AND SETTINGS
NUM_ITERATIONS = 100
GAMES_PER_ITER = 1
EPOCHS_PER_ITER = 10
TRAIN_BATCH_SIZE = 100

LEARNING_RATE = 0.001
HIDDEN_SIZE = 200

WITHOUT_NET = False
QUICK_PLAY = False
RENDER = False
debug = False
print_analytics = False
